#!/usr/bin/env php
<?php

namespace Plugin\PluginTemplate;

require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$app = new Application();

// Get all files from app/Commands
$commands = glob(__DIR__ . '/app/Commands/*.php');

foreach ($commands as $command) {
    $command = str_replace('.php', '', $command);
    $command = str_replace(__DIR__ . '/app/Commands/', '', $command);
    $command = str_replace('/', '\\', $command);
    $command = __NAMESPACE__ . '\\Commands\\' . $command;

    $app->add(new $command);
}

$app->run();
